#!/usr/bin/env perl

use strict;
use warnings;
use JSON; # from_json
use Crypt::Digest::SHA256 qw(sha256_file_hex);
use Env qw($HOME);
use Data::Dumper;
use File::Find;
use List::MoreUtils qw(any);
use Term::ANSIColor qw(:constants);

our $VERSION = '1.0.0';

our $verbose = 1;

open CONFIG, '<', "$HOME/.config/yak/checksums.json";
my $json = join '', <CONFIG>;
close CONFIG;

my $config = from_json($json);

#my $checksum = $config->{'CODE_OF_CONDUCT.md'};

print "$0 : $VERSION\n";

if (defined $ARGV[0]) {
    my $file_checksum = sha256_file_hex($ARGV[0]);
} else {
    find(\&wanted, qw(.));
}

sub wanted {
    my $file = $_;

    if (-f $file and any { $file eq $_ } keys %{$config} ) {

        my $checksum = $config->{$file};
        my $file_checksum = sha256_file_hex($file);

        if ($file_checksum eq $checksum) {
            print STDERR  GREEN, "👍🏻$File::Find::name\n", RESET;
        } else {
            print STDERR RED, "❗️$File::Find::name\n", RESET;
        }
    } elsif (-f $file and $verbose) {
        print STDERR FAINT, "  $File::Find::name skipped\n", RESET;
    }
}

exit 0;
